### ISSUE TITLE
Scrolling in About Us Section

### ISSUE THREAD

**Issue by njosieb** [njosieb/fromhabittoharris#17]
When scrolling through text in the various about us sections, the back and next buttons are only available at the bottom of the screen.  Is there a way for them to be stationary no matter where you are in the paragraph?

Also, when you click back and forth, it keeps you scrolled to where you were the last time you were reading it.  Is there a way to make it that it always starts at the bottom of the paragraph when you click on one of the about us buttons?  Let me know if that doesn't make sense.  :)

**Comment by cvharris** [comment]
Totally makes sense, great catch! We should position the buttons outside the text and scroll back to the top when changing slides. :+1:
